FROM python:3.12-slim
WORKDIR /app
ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1
COPY backend/requirements.txt .
RUN pip install -r requirements.txt
COPY backend /app
CMD ["celery","-A","core","worker","-l","info"]
